Homework one (create-new-project-on-github)
Alesya-23/SpringCourseIn65Apps pull request #1
Opened 2021-02-24 19:08 UTC by Alesya-23

2021-02-24 19:28 UTC, murrcha commented
Папку .idea необходимо добавить в корневой .gitignore, чтобы исключить ее из репозитория

2021-02-24 19:38 UTC, murrcha requested changes

2021-02-24 19:38 UTC, murrcha commented on MyNotFirstAppKotlin/.gitignore
> +.cxx
добавить в исключения .idea

2021-02-27 07:44 UTC, murrcha requested changes
Все хорошо. 
Осталось только немного исправить историю коммитов и само сообщение для коммита (обычно в сообщении указываем что сделано).

Для внесения изменений допустимо делать новый коммит, но тогда будет несколько коммитов по одному PR (это часто засоряет историю, как правило, 1 задача - 1 коммит).
На практике обычно изменения по ходу ревью добавляют уже в текущий коммит локально и пушат их с флагом -f для перезаписи коммита в удаленной ветке.

Несколько коммитов можно схлопнуть (squash) в один (для красивой истории). Для этого можно воспользоваться интерактивным rebase (rebase -i). То есть ожидается, что в данном PR будет только 1 коммит с сообщением, например, created new project или создан новый проект.

2021-03-01 07:13 UTC, murrcha requested changes
Сейчас в PR вижу 2 коммита:
1) add project
2) Merge branch 'main' into create-new-project-on-github
Нужно оставить только один - первый

2021-03-01 10:43 UTC, elestatte87 commented on .gitignore
> +/.idea/caches
.idea
делает тоже самое

В этом смысла нет
/.idea/libraries
/.idea/modules.xml
/.idea/workspace.xml
/.idea/navEditor.xml
/.idea/assetWizardSettings.xml
/.idea/caches

Вообще неблагодарное это дело. Проще ориентироваться на готовое https://github.com/android10/Android-CleanArchitecture-Kotlin/blob/master/.gitignore.

2021-03-01 13:57 UTC, murrcha approved these changes
Все хорошо, можно мержить в основную ветку

2021-03-01 16:54 UTC, merged